### ISSUE TITLE
App won't launch because it cannot find electron-auth0-login

### ISSUE THREAD

**Issue by chasebenedict1** [jbreckmckye/electron-login-test#2]
When I try 'npm start' I get the following error message saying that it cannot find electron-auth0-login which is strange because I ran npm i and it shows that it is installed in the package.json file.

![image](https://user-images.githubusercontent.com/23039320/160266420-4240e119-cf39-44e5-9fb7-dc23439309bc.png)

**Comment by jbreckmckye** [comment]
Yeah, this project doesn't use the NPM package. If you look at the `package.json` you can see it loads from a local version of the project in a sibling directory.

The purpose of this project is to provide a manual test environment when developing `electron-auth0-login`. It's public for anyone who wants to contribute to the repo or wants to see some example code for their own project.

The alternative would be to set it up to use `npm link`. Which I could do, I just haven't ever needed to do so. It's less work for me to test changes, like this.

What were you trying to do?

**Comment by jbreckmckye** [comment]
If all you want to do, is just have the test app install so you can see things working, just change the `package.json` path [here](https://github.com/jbreckmckye/electron-login-test/blob/master/package.json#L14) to a release version and use `npm install`.

**Comment by chasebenedict1** [comment]
Thank you for the response. Yes, I was planning on using it just to see things working and then using it as a template for my electron app that I want to add auth to. I put the most recent version number in the package.json for electron-auth0-login (2.0.1) but I am getting errors still after I run npm start. I ran npm install first.

![image](https://user-images.githubusercontent.com/23039320/160667343-d38da442-d6d9-45a7-84de-d91f9c29b690.png)

**Comment by jbreckmckye** [comment]
Ah yeah. That will be because of the v2.0.1 change. This repo is expecting the function as a default export, but it's no longer supposed to be loaded that way.

**Comment by jbreckmckye** [comment]
Maybe try it after [this](https://github.com/jbreckmckye/electron-login-test/commit/28c3f24b0d2814819ea79d2ea92366533a1e08e4) change
